<a href="https://colab.research.google.com/github/snigdhatanu/Pandas-Practice/blob/main/Copy_of_Missing_Migrants_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Data Cleaning

In [5]:
import numpy as np
import pandas as pd
import matplotlib as plt

In [6]:
data="https://raw.githubusercontent.com/snigdhatanu/Pandas-Practice/refs/heads/main/Global%20Missing%20Migrants%20Dataset.csv"

In [7]:
df=pd.read_csv(data)

In [8]:
df.head()

,Incident Type,Incident year,Reported Month,Region of Origin,Region of Incident,Country of Origin,Number of Dead,Minimum Estimated Number of Missing,Total Number of Dead and Missing,Number of Survivors,Number of Females,Number of Males,Number of Children,Cause of Death,Migration route,Location of death,Information Source,Coordinates,UNSD Geographical Grouping
0,Incident,2014,January,Central America,North America,Guatemala,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,"31.650259, -110.366453",Northern America
1,Incident,2014,January,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,0,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,"31.59713, -111.73756",Northern America
2,Incident,2014,January,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,0,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,"31.94026, -113.01125",Northern America
3,Incident,2014,January,Central America,North America,Mexico,1.0,0,1,0,0,1,0,Violence,US-Mexico border crossing,"near Douglas, Arizona, USA","Ministry of Foreign Affairs Mexico, Pima Count...","31.506777, -109.315632",Northern America
4,Incident,2014,January,Northern Africa,Europe,Sudan,1.0,0,1,2,0,1,0,Harsh environmental conditions / lack of adequ...,NaN,Border between Russia and Estonia,EUBusiness (Agence France-Presse),"59.1551, 28",Northern Europe

In [9]:
df.columns

Index(['Incident Type', 'Incident year', 'Reported Month', 'Region of Origin',
       'Region of Incident', 'Country of Origin', 'Number of Dead',
       'Minimum Estimated Number of Missing',
       'Total Number of Dead and Missing', 'Number of Survivors',
       'Number of Females', 'Number of Males', 'Number of Children',
       'Cause of Death', 'Migration route', 'Location of death',
       'Information Source', 'Coordinates', 'UNSD Geographical Grouping'],
      dtype='object')

In [10]:
df.dtypes

Incident Type                           object
Incident year                            int64
Reported Month                          object
Region of Origin                        object
Region of Incident                      object
Country of Origin                       object
Number of Dead                         float64
Minimum Estimated Number of Missing      int64
Total Number of Dead and Missing         int64
Number of Survivors                      int64
Number of Females                        int64
Number of Males                          int64
Number of Children                       int64
Cause of Death                          object
Migration route                         object
Location of death                       object
Information Source                      object
Coordinates                             object
UNSD Geographical Grouping              object
dtype: object

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13020 entries, 0 to 13019
Data columns (total 19 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Incident Type                        13020 non-null  object
 1   Incident year                        13020 non-null  int64
 2   Reported Month                       13020 non-null  object
 3   Region of Origin                     12998 non-null  object
 4   Region of Incident                   13020 non-null  object
 5   Country of Origin                    13012 non-null  object
 6   Number of Dead                       12470 non-null  float64
 7   Minimum Estimated Number of Missing  13020 non-null  int64
 8   Total Number of Dead and Missing     13020 non-null  int64
 9   Number of Survivors                  13020 non-null  int64
 10  Number of Females                    13020 non-null  int64
 11  Number of Males                      13020 non-null  int64
 12  Number of Children                   13020 non-null  int64
 13  Cause of Death                       13020 non-null  object
 14  Migration route                      9999 non-null   object
 15  Location of death                    13020 non-null  object
 16  Information Source                   13012 non-null  object
 17  Coordinates                          12984 non-null  object
 18  UNSD Geographical Grouping           13019 non-null  object
dtypes: float64(1), int64(7), object(11)
memory usage: 1.9+ MB

In [12]:
df.isnull().sum()

Incident Type                             0
Incident year                             0
Reported Month                            0
Region of Origin                         22
Region of Incident                        0
Country of Origin                         8
Number of Dead                          550
Minimum Estimated Number of Missing       0
Total Number of Dead and Missing          0
Number of Survivors                       0
Number of Females                         0
Number of Males                           0
Number of Children                        0
Cause of Death                            0
Migration route                        3021
Location of death                         0
Information Source                        8
Coordinates                              36
UNSD Geographical Grouping                1
dtype: int64

In [13]:
df_nullcheck=df.isnull().any(axis=1)
df_null=df[df_nullcheck]
df_null.sample(10)

,Incident Type,Incident year,Reported Month,Region of Origin,Region of Incident,Country of Origin,Number of Dead,Minimum Estimated Number of Missing,Total Number of Dead and Missing,Number of Survivors,Number of Females,Number of Males,Number of Children,Cause of Death,Migration route,Location of death,Information Source,Coordinates,UNSD Geographical Grouping
4307,Incident,2018,May,Central America,Central America,Guatemala,1.0,0,1,106,0,1,0,Violence,NaN,"Road between San Francisco Telixtlahuaca, Oaxa...","El Diario, NVI Noticias","17.31572257, -96.92453667",Central America
5964,Incident,2019,May,Latin America / Caribbean (P),Central America,Unknown,1.0,0,1,1,0,1,0,Vehicle accident / death linked to hazardous t...,NaN,"Train tracks in Mesillas, Ramos Arizpe, Coahui...","Newsweek Mexico, Linea Directa Portal","25.805945517, -101.007119515",Central America
11223,Incident,2022,August,Caribbean,Central America,Cuba,1.0,0,1,0,1,0,0,Vehicle accident / death linked to hazardous t...,NaN,At kilometer 300 of the Cordoba-Veracruz highw...,"Vanguardia de Veracruz,El Mundo","18.78552323, -96.514013",Central America
9019,Incident,2021,June,Southern Asia,South America,Bangladesh,NaN,15,15,6,0,0,0,Drowning,NaN,In the Caribbean Sea near Puerto Escondido of ...,Noticias Caracol,"9.038525113, -76.33946531",South America
1086,Incident,2015,December,Eastern Africa (P),Eastern Africa,Unknown,1.0,0,1,0,0,0,0,Violence,NaN,"Tuulo Barwaaqo, Somalia",Mixed Migration Monitoring Mechanism Initative...,"5.152149, 46.199616",Eastern Africa
6655,Incident,2019,September,Sub-Saharan Africa (P),Western Africa,Unknown,1.0,0,1,0,0,1,1,Vehicle accident / death linked to hazardous t...,NaN,"Sevare, Mali",Mixed Migration Monitoring Mechanism Initiativ...,"-4.095111, 14.52279",Western Africa
4633,Incident,2018,July,Southern Asia,Europe,Pakistan,1.0,0,1,0,0,1,0,Violence,NaN,Near Greek border with the former Yugoslav Rep...,Lahore Daily Times,"41.076758, 22.23965977",Southern Europe
7326,Incident,2020,February,Unknown,Northern Africa,Unknown,NaN,14,14,14,0,0,2,Drowning,Western Africa / Atlantic route to the Canary ...,"Off the coast of Dakhla, Western Sahara - en r...","Alarm Phone, Caminando Fronteras","23.693325, -15.941875",Uncategorized
11964,Incident,2022,September,Southern Asia,Southern Asia,Afghanistan,1.0,0,1,0,0,1,0,Sickness / lack of access to adequate healthcare,NaN,"Balghali village, Kohistanat district, Sarepul...",IOM Afghanistan,"35.4030708, 65.9511993",Southern Asia
9631,Incident,2021,June,Sub-Saharan Africa (P),Northern Africa,Unknown,NaN,67,67,0,12,55,0,Drowning,Western Africa / Atlantic route to the Canary ...,Unspecified location in the Atlantic off the c...,"Alarm Phone, Caminando Fronteras","33.01479981, 12.54897854",Uncategorized

In [14]:
df_null.columns

Index(['Incident Type', 'Incident year', 'Reported Month', 'Region of Origin',
       'Region of Incident', 'Country of Origin', 'Number of Dead',
       'Minimum Estimated Number of Missing',
       'Total Number of Dead and Missing', 'Number of Survivors',
       'Number of Females', 'Number of Males', 'Number of Children',
       'Cause of Death', 'Migration route', 'Location of death',
       'Information Source', 'Coordinates', 'UNSD Geographical Grouping'],
      dtype='object')

In [15]:
origin = df.isnull()
df_origin = df[origin]
df_origin.sample(10)

,Incident Type,Incident year,Reported Month,Region of Origin,Region of Incident,Country of Origin,Number of Dead,Minimum Estimated Number of Missing,Total Number of Dead and Missing,Number of Survivors,Number of Females,Number of Males,Number of Children,Cause of Death,Migration route,Location of death,Information Source,Coordinates,UNSD Geographical Grouping
3771,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7068,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8278,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10714,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7050,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9259,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1397,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7267,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
origin = df[['Region of Origin','Country of Origin']].isnull().any(axis=1)
df_origin = df[origin]
df_origin.sample(10)

,Incident Type,Incident year,Reported Month,Region of Origin,Region of Incident,Country of Origin,Number of Dead,Minimum Estimated Number of Missing,Total Number of Dead and Missing,Number of Survivors,Number of Females,Number of Males,Number of Children,Cause of Death,Migration route,Location of death,Information Source,Coordinates,UNSD Geographical Grouping
12930,Incident,2023,February,NaN,Northern Africa,Unknown,1.0,0,1,0,0,0,0,Harsh environmental conditions / lack of adequ...,Sahara Desert crossing,"Al-Jawf, AlKufra, Libya",IOM Libya Displacement Tracking Matrix,"24.20642056, 23.290271",Northern Africa
12926,Incident,2023,February,NaN,Northern Africa,Nigeria,1.0,0,1,0,0,1,0,Vehicle accident / death linked to hazardous t...,NaN,"Rass Al-Magil, Misrata, Libya",IOM Libya Displacement Tracking Matrix,"32.33801861, 15.044267",Northern Africa
12929,Incident,2023,February,NaN,Northern Africa,Unknown,3.0,0,3,0,1,2,0,Mixed or unknown,Sahara Desert crossing,"Al-Jawf, AlKufra, Libya",IOM Libya Displacement Tracking Matrix,"24.20642056, 23.290271",Northern Africa
1217,Incident,2016,January,NaN,Mediterranean,"Afghanistan,Iraq,Syrian Arab Republic",39.0,0,39,75,0,0,5,Drowning,Eastern Mediterranean,"between Ayvacik, Canakkale, Türkiye and Lesvos...",Turkish Coast Guard via IOM Athens. AFP and th...,"39.2893824, 26.4734281",Uncategorized
12937,Incident,2023,April,NaN,Northern Africa,Nigeria,2.0,0,2,0,0,2,0,Vehicle accident / death linked to hazardous t...,Sahara Desert crossing,"Alchuirif El gharbia, Ashshwayrif, Libya",IOM Libya Displacement Tracking Matrix,"14.22490057, 65.555267",Northern Africa
12940,Incident,2023,May,NaN,Northern Africa,Unknown,5.0,0,5,8,0,0,0,Vehicle accident / death linked to hazardous t...,Sahara Desert crossing,"Bouzreq, AlKufra, Libya",IOM Libya Displacement Tracking Matrix,"24.92367718, 22.107087",Northern Africa
12931,Incident,2023,March,NaN,Northern Africa,Chad,1.0,0,1,0,0,1,0,Violence,Sahara Desert crossing,"Gatroun, Al-Qatroun, Libya",IOM Libya Displacement Tracking Matrix,"24.94447643, 14.627779",Northern Africa
12943,Incident,2023,May,NaN,Northern Africa,Unknown,1.0,0,1,6,0,7,0,Vehicle accident / death linked to hazardous t...,Sahara Desert crossing,"Alchuirif El gharbia, Ashshwayrif, Libya",IOM Libya Displacement Tracking Matrix,"14.22490057, 65.555267",Northern Africa
185,Incident,2014,August,Unknown,Mediterranean,NaN,0.0,100,100,0,0,0,0,Drowning,Central Mediterranean,"Off the shore of al-Qarbouli, Libya",Press Association,"32.8879, 14",Uncategorized
974,Incident,2015,December,Central America,North America,NaN,1.0,0,1,0,0,1,0,Drowning,US-Mexico border crossing,"All American Canal, CA near Calexico",El Mexicano,"32.668019, -115.502043",Northern America

In [17]:
df_origin['Region of Origin'].unique()

array(['Unknown', 'South-eastern Asia', 'Latin America / Caribbean (P)',
       'Central America', 'Eastern Africa (P)', nan], dtype=object)

In [18]:
df_origin["Country of Origin"].unique()

array([nan, 'Afghanistan,Iraq,Syrian Arab Republic', 'Sudan', 'Egypt',
       'Unknown', 'Nigeria', 'Chad', 'Syrian Arab Republic', 'Mauritania',
       'Bangladesh'], dtype=object)

In [19]:
df_origin_country=df_origin[["Region of Origin","Country of Origin"]]
df_origin_country

                    Region of Origin                      Country of Origin
132                          Unknown                                    NaN
185                          Unknown                                    NaN
254                          Unknown                                    NaN
423               South-eastern Asia                                    NaN
761    Latin America / Caribbean (P)                                    NaN
922                  Central America                                    NaN
974                  Central America                                    NaN
1003              Eastern Africa (P)                                    NaN
1217                             NaN  Afghanistan,Iraq,Syrian Arab Republic
12923                            NaN                                  Sudan
12924                            NaN                                  Egypt
12925                            NaN                                Unknown
12926                            NaN                                Nigeria
12927                            NaN                                  Sudan
12928                            NaN                                Unknown
12929                            NaN                                Unknown
12930                            NaN                                Unknown
12931                            NaN                                   Chad
12932                            NaN                   Syrian Arab Republic
12933                            NaN                                Unknown
12934                            NaN                                Unknown
12935                            NaN                             Mauritania
12936                            NaN                                Unknown
12937                            NaN                                Nigeria
12938                            NaN                                Unknown
12939                            NaN                                  Egypt
12940                            NaN                                Unknown
12941                            NaN                             Bangladesh
12942                            NaN                                Unknown
12943                            NaN                                Unknown

In [20]:
df["Country of Origin"]=np.where((df["Region of Origin"]=="Unknown")&(df["Country of Origin"].isna()),"unknown",df["Country of Origin"])

In [21]:
df["Country of Origin"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 13020 entries, 0 to 13019
Series name: Country of Origin
Non-Null Count  Dtype
--------------  -----
13015 non-null  object
dtypes: object(1)
memory usage: 101.8+ KB

In [22]:
df["Country of Origin"].isna().sum()

5

In [23]:
df_cleaning=df[["Country of Origin","Region of Origin"]].isna().any(axis=1)
df_cleaning=df[df_cleaning]
df_cleaning

,Incident Type,Incident year,Reported Month,Region of Origin,Region of Incident,Country of Origin,Number of Dead,Minimum Estimated Number of Missing,Total Number of Dead and Missing,Number of Survivors,Number of Females,Number of Males,Number of Children,Cause of Death,Migration route,Location of death,Information Source,Coordinates,UNSD Geographical Grouping
423,Incident,2015,May,South-eastern Asia,South-eastern Asia,NaN,2.0,0,2,0,0,0,0,Mixed or unknown,NaN,"Trafficking camps in Phang Nga province, Thailand",The Guardian,"8.4501414, 98.525532",South-eastern Asia
761,Incident,2015,October,Latin America / Caribbean (P),Central America,NaN,1.0,0,1,0,0,1,0,Violence,NaN,"Xaloztoc, Tlaxcala, Mexico",Agenda Tlaxcala,"19.408, -98.052",Central America
922,Incident,2015,November,Central America,North America,NaN,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,"31.511, -111.561833",Northern America
974,Incident,2015,December,Central America,North America,NaN,1.0,0,1,0,0,1,0,Drowning,US-Mexico border crossing,"All American Canal, CA near Calexico",El Mexicano,"32.668019, -115.502043",Northern America
1003,Incident,2015,December,Eastern Africa (P),Northern Africa,NaN,2.0,0,2,0,0,0,0,Sickness / lack of access to adequate healthcare,Sahara Desert crossing,"Sabha, Libya",Mixed Migration Monitoring Mechanism Initative...,"27.032288, 14.456116",Northern Africa
1217,Incident,2016,January,NaN,Mediterranean,"Afghanistan,Iraq,Syrian Arab Republic",39.0,0,39,75,0,0,5,Drowning,Eastern Mediterranean,"between Ayvacik, Canakkale, Türkiye and Lesvos...",Turkish Coast Guard via IOM Athens. AFP and th...,"39.2893824, 26.4734281",Uncategorized
12923,Incident,2023,January,NaN,Northern Africa,Sudan,1.0,0,1,0,0,1,0,Sickness / lack of access to adequate healthcare,Sahara Desert crossing,"Al-Jawf, AlKufra, Libya",IOM Libya Displacement Tracking Matrix,"24.22092653, 23.291791",Northern Africa
12924,Incident,2023,January,NaN,Northern Africa,Egypt,1.0,0,1,0,0,1,0,Violence,Sahara Desert crossing,"Qondofah, Benghazi, Libya",IOM Libya Displacement Tracking Matrix,"32.029039, 20.016156",Northern Africa
12925,Incident,2023,January,NaN,Northern Africa,Unknown,1.0,0,1,0,0,1,0,Sickness / lack of access to adequate healthcare,Sahara Desert crossing,"Al-Madina, Tobruk, Libya",IOM Libya Displacement Tracking Matrix,"32.09704552, 23.991754",Northern Africa
12926,Incident,2023,February,NaN,Northern Africa,Nigeria,1.0,0,1,0,0,1,0,Vehicle accident / death linked to hazardous t...,NaN,"Rass Al-Magil, Misrata, Libya",IOM Libya Displacement Tracking Matrix,"32.33801861, 15.044267",Northern Africa
12927,Incident,2023,February,NaN,Northern Africa,Sudan,1.0,0,1,0,0,1,0,Accidental death,Sahara Desert crossing,"Al-Jawf, AlKufra, Libya",IOM Libya Displacement Tracking Matrix,"24.20637163, 23.290346",Northern Africa
12928,Incident,2023,January,NaN,Northern Africa,Unknown,3.0,0,3,4,0,7,0,Vehicle accident / death linked to hazardous t...,Sahara Desert crossing,"Alchuirif El gharbia, Ashshwayrif, Libya",IOM Libya Displacement Tracking Matrix,"31.04216493, 14.431426",Northern Africa
12929,Incident,2023,February,NaN,Northern Africa,Unknown,3.0,0,3,0,1,2,0,Mixed or unknown,Sahara Desert crossing,"Al-Jawf, AlKufra, Libya",IOM Libya Displacement Tracking Matrix,"24.20642056, 23.290271",Northern Africa
12930,Incident,2023,February,NaN,Northern Africa,Unknown,1.0,0,1,0,0,0,0,Harsh environmental conditions / lack of adequ...,Sahara Desert crossing,"Al-Jawf, AlKufra, Libya",IOM Libya Displacement Tracking Matrix,"24.20642056, 23.290271",Northern Africa
12931,Incident,2023,March,NaN,Northern Africa,Chad,1.0,0,1,0,0,1,0,Violence,Sahara Desert crossing,"Gatroun, Al-Qatroun, Libya",IOM Libya Displacement Tracking Matrix,"24.94447643, 14.627779",Northern Africa
12932,Incident,2023,March,NaN,Northern Africa,Syrian Arab Republic,1.0,0,1,1,0,2,0,Harsh environmental conditions / lack of adequ...,Sahara Desert crossing,"Umm Sa'ad, Libya",IOM Libya Displacement Tracking Matrix,"24.20642056, 23.290271",Northern Africa
12933,Incident,2023,March,NaN,Northern Africa,Unknown,2.0,6,8,8,0,8,0,Vehicle accident / death linked to hazardous t...,Sahara Desert crossing,"Bazimah in the Soutth of Rbaaniah, Al-Kufra, L...",IOM Libya Displacement Tracking Matrix,"21.95627, 24.25597",Northern Africa
12934,Incident,2023,March,NaN,Northern Africa,Unknown,1.0,0,1,0,0,1,0,Sickness / lack of access to adequate healthcare,Sahara Desert crossing,"Qatrun, Al-gatroun, Libya",IOM Libya Displacement Tracking Matrix,"27.04400604, 14.436574",Northern Africa
12935,Incident,2023,March,NaN,Northern Africa,Mauritania,2.0,0,2,3,0,2,1,Vehicle accident / death linked to hazardous t...,Sahara Desert crossing,"Qatrun, Al-gatroun, Libya",IOM Libya Displacement Tracking Matrix,"27.04400604, 14.436574",Northern Africa
12936,Incident,2023,April,NaN,Northern Africa,Unknown,6.0,0,6,2,0,8,0,Vehicle accident / death linked to hazardous t...,Sahara Desert crossing,"Bint Bayya, Wadi al Shatii District, Libya",IOM Libya Displacement Tracking Matrix,"27.48775812, 13.360607",Northern Africa
12937,Incident,2023,April,NaN,Northern Africa,Nigeria,2.0,0,2,0,0,2,0,Vehicle accident / death linked to hazardous t...,Sahara Desert crossing,"Alchuirif El gharbia, Ashshwayrif, Libya",IOM Libya Displacement Tracking Matrix,"14.22490057, 65.555267",Northern Africa
12938,Incident,2023,April,NaN,Northern Africa,Unknown,8.0,0,8,18,0,8,0,Mixed or unknown,Sahara Desert crossing,"Brak, Libya",IOM Libya Displacement Tracking Matrix,"27.54179645, 14.300551",Northern Africa
12939,Incident,2023,April,NaN,Northern Africa,Egypt,1.0,0,1,0,0,1,0,Violence,Sahara Desert crossing,"Umm Sa'ad, Libya",IOM Libya Displacement Tracking Matrix,"31.6488315, 25.052252",Northern Africa
12940,Incident,2023,May,NaN,Northern Africa,Unknown,5.0,0,5,8,0,0,0,Vehicle accident / death linked to hazardous t...,Sahara Desert crossing,"Bouzreq, AlKufra, Libya",IOM Libya Displacement Tracking Matrix,"24.92367718, 22.107087",Northern Africa
12941,Incident,2023,May,NaN,Northern Africa,Bangladesh,8.0,0,8,0,0,8,0,Vehicle accident / death linked to hazardous t...,Sahara Desert crossing,"Qaminis, Libya",IOM Libya Displacement Tracking Matrix,"31.65071241, 20.011192",Northern Africa
12942,Incident,2023,May,NaN,Northern Africa,Unknown,1.0,0,1,0,0,1,0,Accidental death,Sahara Desert crossing,"Umm Sa'ad, Libya",IOM Libya Displacement Tracking Matrix,"31.6124278, 25.046548",Northern Africa
12943,Incident,2023,May,NaN,Northern Africa,Unknown,1.0,0,1,6,0,7,0,Vehicle accident / death linked to hazardous t...,Sahara Desert crossing,"Alchuirif El gharbia, Ashshwayrif, Libya",IOM Libya Displacement Tracking Matrix,"14.22490057, 65.555267",Northern Africa

In [24]:
df_cleaning=df_cleaning[["Region of Origin","Country of Origin"]]
df_cleaning

                    Region of Origin                      Country of Origin
423               South-eastern Asia                                    NaN
761    Latin America / Caribbean (P)                                    NaN
922                  Central America                                    NaN
974                  Central America                                    NaN
1003              Eastern Africa (P)                                    NaN
1217                             NaN  Afghanistan,Iraq,Syrian Arab Republic
12923                            NaN                                  Sudan
12924                            NaN                                  Egypt
12925                            NaN                                Unknown
12926                            NaN                                Nigeria
12927                            NaN                                  Sudan
12928                            NaN                                Unknown
12929                            NaN                                Unknown
12930                            NaN                                Unknown
12931                            NaN                                   Chad
12932                            NaN                   Syrian Arab Republic
12933                            NaN                                Unknown
12934                            NaN                                Unknown
12935                            NaN                             Mauritania
12936                            NaN                                Unknown
12937                            NaN                                Nigeria
12938                            NaN                                Unknown
12939                            NaN                                  Egypt
12940                            NaN                                Unknown
12941                            NaN                             Bangladesh
12942                            NaN                                Unknown
12943                            NaN                                Unknown

In [25]:
df_cleaning1=df_cleaning[(df_cleaning["Country of Origin"].notna()) & (df_cleaning["Region of Origin"].isna())]
df_cleaning1

      Region of Origin                      Country of Origin
1217               NaN  Afghanistan,Iraq,Syrian Arab Republic
12923              NaN                                  Sudan
12924              NaN                                  Egypt
12925              NaN                                Unknown
12926              NaN                                Nigeria
12927              NaN                                  Sudan
12928              NaN                                Unknown
12929              NaN                                Unknown
12930              NaN                                Unknown
12931              NaN                                   Chad
12932              NaN                   Syrian Arab Republic
12933              NaN                                Unknown
12934              NaN                                Unknown
12935              NaN                             Mauritania
12936              NaN                                Unknown
12937              NaN                                Nigeria
12938              NaN                                Unknown
12939              NaN                                  Egypt
12940              NaN                                Unknown
12941              NaN                             Bangladesh
12942              NaN                                Unknown
12943              NaN                                Unknown

In [26]:
df["Country of Origin"].isna().sum()

5

In [27]:
df["Region of Origin"]=np.where((df["Region of Origin"].isna()) & (df["Country of Origin"]=="Unknown"),"Unknown",df["Region of Origin"])

In [28]:
df_cleaning1=df[["Region of Origin","Country of Origin"]].isna().any(axis=1)
df_cleaning1=df[df_cleaning1]
df_cleaning1[["Region of Origin","Country of Origin"]]

                    Region of Origin                      Country of Origin
423               South-eastern Asia                                    NaN
761    Latin America / Caribbean (P)                                    NaN
922                  Central America                                    NaN
974                  Central America                                    NaN
1003              Eastern Africa (P)                                    NaN
1217                             NaN  Afghanistan,Iraq,Syrian Arab Republic
12923                            NaN                                  Sudan
12924                            NaN                                  Egypt
12926                            NaN                                Nigeria
12927                            NaN                                  Sudan
12931                            NaN                                   Chad
12932                            NaN                   Syrian Arab Republic
12935                            NaN                             Mauritania
12937                            NaN                                Nigeria
12939                            NaN                                  Egypt
12941                            NaN                             Bangladesh

In [29]:
df["Country of Origin"]=np.where(df["Country of Origin"].isna(),"unknown",df["Country of Origin"])

In [30]:
df["Country of Origin"].isna().sum()

0

In [31]:
df[["Region of Origin","Country of Origin"]].isna().sum()

Region of Origin     11
Country of Origin     0
dtype: int64

In [32]:
df_cleaning1=df[["Region of Origin","Country of Origin"]].isna().any(axis=1)
df_cleaning1=df[df_cleaning1]
df_cleaning1[["Region of Origin","Country of Origin"]]

      Region of Origin                      Country of Origin
1217               NaN  Afghanistan,Iraq,Syrian Arab Republic
12923              NaN                                  Sudan
12924              NaN                                  Egypt
12926              NaN                                Nigeria
12927              NaN                                  Sudan
12931              NaN                                   Chad
12932              NaN                   Syrian Arab Republic
12935              NaN                             Mauritania
12937              NaN                                Nigeria
12939              NaN                                  Egypt
12941              NaN                             Bangladesh

In [33]:
df_cleaning2 = df[((df["Country of Origin"]=="Afghanistan,Iraq,Syrian Arab Republic") |
                   (df["Country of Origin"]=="Sudan") |
                   (df["Country of Origin"]=="Egypt") |
                   (df["Country of Origin"]=="Nigeria") |
                   (df["Country of Origin"]=="Bangladesh"))]
df_cleaning3=df.loc[df_cleaning2.index].drop_duplicates()
df_cleaning3[["Region of Origin","Country of Origin"]]

      Region of Origin Country of Origin
4      Northern Africa             Sudan
28       Southern Asia        Bangladesh
89     Northern Africa             Sudan
229    Northern Africa             Sudan
244    Northern Africa             Sudan
...                ...               ...
12926              NaN           Nigeria
12927              NaN             Sudan
12937              NaN           Nigeria
12939              NaN             Egypt
12941              NaN        Bangladesh

[166 rows x 2 columns]

In [34]:
df_cleaning3=df["Country of Origin"]=="Sudan"
df_cleaning3=df[df_cleaning3]
df_cleaning3=df_cleaning3[["Region of Origin","Country of Origin"]]
df_cleaning3.head(5)

    Region of Origin Country of Origin
4    Northern Africa             Sudan
89   Northern Africa             Sudan
229  Northern Africa             Sudan
244  Northern Africa             Sudan
518  Northern Africa             Sudan

In [35]:
df["Region of Origin"]=np.where((df["Region of Origin"]=="Unknown") & (df["Country of Origin"]=="Sudan"), "Northern Africa",df["Region of Origin"])
df

,Incident Type,Incident year,Reported Month,Region of Origin,Region of Incident,Country of Origin,Number of Dead,Minimum Estimated Number of Missing,Total Number of Dead and Missing,Number of Survivors,Number of Females,Number of Males,Number of Children,Cause of Death,Migration route,Location of death,Information Source,Coordinates,UNSD Geographical Grouping
0,Incident,2014,January,Central America,North America,Guatemala,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,"31.650259, -110.366453",Northern America
1,Incident,2014,January,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,0,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,"31.59713, -111.73756",Northern America
2,Incident,2014,January,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,0,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,"31.94026, -113.01125",Northern America
3,Incident,2014,January,Central America,North America,Mexico,1.0,0,1,0,0,1,0,Violence,US-Mexico border crossing,"near Douglas, Arizona, USA","Ministry of Foreign Affairs Mexico, Pima Count...","31.506777, -109.315632",Northern America
4,Incident,2014,January,Northern Africa,Europe,Sudan,1.0,0,1,2,0,1,0,Harsh environmental conditions / lack of adequ...,NaN,Border between Russia and Estonia,EUBusiness (Agence France-Presse),"59.1551, 28",Northern Europe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13015,Incident,2023,July,Western Asia,Western Asia,Syrian Arab Republic,4.0,0,4,0,0,4,0,Vehicle accident / death linked to hazardous t...,Türkiye-Europe land route,"In Ipsala, Edirne province, Türkiye - travelli...","Andalou Agency, Son Dakika, Orient News","40.91271268, 26.369657",Western Asia
13016,Incident,2023,July,Western Africa (P),Western Asia,Unknown,2.0,0,2,0,0,2,0,Vehicle accident / death linked to hazardous t...,Türkiye-Europe land route,"At the Kapıkule Türkiye-Bulgaria Border Gate, ...","Son Dakika, Hurriyet","41.71697242, 26.351489",Western Asia
13017,Incident,2023,July,Western Africa,Northern Africa,Senegal,13.0,0,13,6,0,0,0,Drowning,Western Africa / Atlantic route to the Canary ...,"Off the coasts of Dakhla, Western Sahara - 6 s...","Barron's News, InfoMigrants, IOM Morrocco","23.72836078, -15.901632",Uncategorized
13018,Incident,2023,July,Mixed,Northern Africa,Unknown,6.0,0,6,48,0,0,0,Drowning,Western Africa / Atlantic route to the Canary ...,"Unspecified location off the coast of Nador, M...","El Nashra, Swiss Info; CGTN, IOM Morrocco","35.17187365, -2.903182",Uncategorized
13019,Incident,2023,July,Western Africa (P),Western Africa,Unknown,16.0,37,53,2,2,0,0,Drowning,Western Africa / Atlantic route to the Canary ...,"Off the coast of Ouakam, Dakar, Senegal",IOM Senegal,"14.71870705, -17.506255",Uncategorized

In [36]:
df["Region of Origin"]=np.where((df["Region of Origin"].isna()) & (df["Country of Origin"]=="Sudan"), "Northern Africa",df["Region of Origin"])
df[["Country of Origin","Region of Origin"]]

          Country of Origin               Region of Origin
0                 Guatemala                Central America
1                   Unknown  Latin America / Caribbean (P)
2                   Unknown  Latin America / Caribbean (P)
3                    Mexico                Central America
4                     Sudan                Northern Africa
...                     ...                            ...
13015  Syrian Arab Republic                   Western Asia
13016               Unknown             Western Africa (P)
13017               Senegal                 Western Africa
13018               Unknown                          Mixed
13019               Unknown             Western Africa (P)

[13020 rows x 2 columns]

In [37]:
df[["Country of Origin","Region of Origin"]].isna().sum()

Country of Origin    0
Region of Origin     9
dtype: int64

In [38]:
df.isna().sum()

Incident Type                             0
Incident year                             0
Reported Month                            0
Region of Origin                          9
Region of Incident                        0
Country of Origin                         0
Number of Dead                          550
Minimum Estimated Number of Missing       0
Total Number of Dead and Missing          0
Number of Survivors                       0
Number of Females                         0
Number of Males                           0
Number of Children                        0
Cause of Death                            0
Migration route                        3021
Location of death                         0
Information Source                        8
Coordinates                              36
UNSD Geographical Grouping                1
dtype: int64

In [39]:
df_cleaning4=df[["Country of Origin","Region of Origin"]].isna().any(axis=1)
df_cleaning4=df[df_cleaning4]
df_cleaning4[["Region of Origin","Country of Origin"]]

      Region of Origin                      Country of Origin
1217               NaN  Afghanistan,Iraq,Syrian Arab Republic
12924              NaN                                  Egypt
12926              NaN                                Nigeria
12931              NaN                                   Chad
12932              NaN                   Syrian Arab Republic
12935              NaN                             Mauritania
12937              NaN                                Nigeria
12939              NaN                                  Egypt
12941              NaN                             Bangladesh

In [40]:
df_cleaning4["Region of Origin"]=np.where((((df_cleaning4["Country of Origin"]=="Afghanistan,Iraq,Syrian Arab Republic") |
                   (df_cleaning4["Country of Origin"]=="Sudan") |
                   (df_cleaning4["Country of Origin"]=="Egypt") |
                   (df_cleaning4["Country of Origin"]=="Nigeria") |
                   (df_cleaning4["Country of Origin"]=="Bangladesh")))
                         & (df_cleaning4["Region of Origin"].isna()),"Unknown",df_cleaning4["Region of Origin"])


df_cleaning4[["Region of Origin","Country of Origin"]]

<ipython-input-40-e7d94e2e6fc4>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaning4["Region of Origin"]=np.where((((df_cleaning4["Country of Origin"]=="Afghanistan,Iraq,Syrian Arab Republic") |

      Region of Origin                      Country of Origin
1217           Unknown  Afghanistan,Iraq,Syrian Arab Republic
12924          Unknown                                  Egypt
12926          Unknown                                Nigeria
12931              NaN                                   Chad
12932              NaN                   Syrian Arab Republic
12935              NaN                             Mauritania
12937          Unknown                                Nigeria
12939          Unknown                                  Egypt
12941          Unknown                             Bangladesh

In [41]:
df["Region of Origin"]=np.where(((df["Country of Origin"]=="Chad")|
                                         (df["Country of Origin"]=="Syrian Arab Republic")|
                                         (df["Country of Origin"]=="Mauritania"))
                                         & (df["Region of Origin"].isna()),"Unknown",df["Region of Origin"])

In [42]:
df.loc[((df["Country of Origin"] == "Chad") |
                 (df["Country of Origin"] == "Syrian Arab Republic") |
                 (df["Country of Origin"] == "Mauritania")) &
                pd.isna(df["Region of Origin"]), "Region of Origin"] = "Unknown"

In [43]:
df_cleaning5=df[["Country of Origin","Region of Origin"]].isna().any(axis=1)
df_cleaning5=df[df_cleaning5]
df_cleaning5[["Region of Origin","Country of Origin"]]

      Region of Origin                      Country of Origin
1217               NaN  Afghanistan,Iraq,Syrian Arab Republic
12924              NaN                                  Egypt
12926              NaN                                Nigeria
12937              NaN                                Nigeria
12939              NaN                                  Egypt
12941              NaN                             Bangladesh

In [44]:
df["Region of Origin"]=df["Region of Origin"].fillna("Unknown")

In [45]:
df.isna().sum()

Incident Type                             0
Incident year                             0
Reported Month                            0
Region of Origin                          0
Region of Incident                        0
Country of Origin                         0
Number of Dead                          550
Minimum Estimated Number of Missing       0
Total Number of Dead and Missing          0
Number of Survivors                       0
Number of Females                         0
Number of Males                           0
Number of Children                        0
Cause of Death                            0
Migration route                        3021
Location of death                         0
Information Source                        8
Coordinates                              36
UNSD Geographical Grouping                1
dtype: int64

In [46]:
df.head()

,Incident Type,Incident year,Reported Month,Region of Origin,Region of Incident,Country of Origin,Number of Dead,Minimum Estimated Number of Missing,Total Number of Dead and Missing,Number of Survivors,Number of Females,Number of Males,Number of Children,Cause of Death,Migration route,Location of death,Information Source,Coordinates,UNSD Geographical Grouping
0,Incident,2014,January,Central America,North America,Guatemala,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,"31.650259, -110.366453",Northern America
1,Incident,2014,January,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,0,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,"31.59713, -111.73756",Northern America
2,Incident,2014,January,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,0,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,Pima County Office of the Medical Examiner (PC...,"31.94026, -113.01125",Northern America
3,Incident,2014,January,Central America,North America,Mexico,1.0,0,1,0,0,1,0,Violence,US-Mexico border crossing,"near Douglas, Arizona, USA","Ministry of Foreign Affairs Mexico, Pima Count...","31.506777, -109.315632",Northern America
4,Incident,2014,January,Northern Africa,Europe,Sudan,1.0,0,1,2,0,1,0,Harsh environmental conditions / lack of adequ...,NaN,Border between Russia and Estonia,EUBusiness (Agence France-Presse),"59.1551, 28",Northern Europe

In [47]:
df.isna().sum()

Incident Type                             0
Incident year                             0
Reported Month                            0
Region of Origin                          0
Region of Incident                        0
Country of Origin                         0
Number of Dead                          550
Minimum Estimated Number of Missing       0
Total Number of Dead and Missing          0
Number of Survivors                       0
Number of Females                         0
Number of Males                           0
Number of Children                        0
Cause of Death                            0
Migration route                        3021
Location of death                         0
Information Source                        8
Coordinates                              36
UNSD Geographical Grouping                1
dtype: int64

In [48]:
df_dead=df["Number of Dead"].isna()
df_dead=df[df_dead]
df_dead["Number of Dead"]

295     NaN
336     NaN
351     NaN
378     NaN
379     NaN
         ..
12946   NaN
12950   NaN
12966   NaN
12967   NaN
13011   NaN
Name: Number of Dead, Length: 550, dtype: float64

In [49]:
Average=df["Number of Dead"].mean()
Average=round(Average)
print(Average)

3

In [50]:
df["Number of Dead"].sample(20)

4644      NaN
2302     18.0
2390      1.0
1985     20.0
2549      1.0
5226      1.0
10286     2.0
8262      1.0
8117      1.0
2517      3.0
5249      1.0
7789      5.0
6618      1.0
8237      1.0
3685      1.0
5173      1.0
12093     1.0
4856      6.0
3895      1.0
9231      NaN
Name: Number of Dead, dtype: float64

In [51]:
df["Number of Dead"]=df["Number of Dead"].fillna(0)

In [52]:
df["Number of Dead"].isna().sum()

0

In [53]:
df.isna().sum()

Incident Type                             0
Incident year                             0
Reported Month                            0
Region of Origin                          0
Region of Incident                        0
Country of Origin                         0
Number of Dead                            0
Minimum Estimated Number of Missing       0
Total Number of Dead and Missing          0
Number of Survivors                       0
Number of Females                         0
Number of Males                           0
Number of Children                        0
Cause of Death                            0
Migration route                        3021
Location of death                         0
Information Source                        8
Coordinates                              36
UNSD Geographical Grouping                1
dtype: int64

In [54]:
 df[["Cause of Death","Migration route"]].head(20)

,Cause of Death,Migration route
0,Mixed or unknown,US-Mexico border crossing
1,Mixed or unknown,US-Mexico border crossing
2,Mixed or unknown,US-Mexico border crossing
3,Violence,US-Mexico border crossing
4,Harsh environmental conditions / lack of adequ...,NaN
5,Violence,US-Mexico border crossing
6,Drowning,Eastern Mediterranean
7,Mixed or unknown,US-Mexico border crossing
8,Mixed or unknown,US-Mexico border crossing
9,Mixed or unknown,US-Mexico border crossing
10,Mixed or unknown,US-Mexico border crossing
11,Mixed or unknown,US-Mexico border crossing
12,Mixed or unknown,US-Mexico border crossing
13,Mixed or unknown,US-Mexico border crossing
14,Vehicle accident / death linked to hazardous t...,English Channel to the UK
15,Drowning,Caribbean to US
16,Sickness / lack of access to adequate healthcare,NaN
17,Violence,Western Mediterranean
18,Mixed or unknown,US-Mexico border crossing
19,Mixed or unknown,US-Mexico border crossing

In [55]:
df_cause=df[["Cause of Death","Migration route"]].isna().any(axis=1)
df_cause=df[df_cause]
df_cause[["Cause of Death","Migration route"]]

                                          Cause of Death Migration route
4      Harsh environmental conditions / lack of adequ...             NaN
16      Sickness / lack of access to adequate healthcare             NaN
28                                              Violence             NaN
33     Vehicle accident / death linked to hazardous t...             NaN
34     Vehicle accident / death linked to hazardous t...             NaN
...                                                  ...             ...
13004                                   Mixed or unknown             NaN
13005                                   Mixed or unknown             NaN
13006                                   Mixed or unknown             NaN
13011                                   Mixed or unknown             NaN
13012  Harsh environmental conditions / lack of adequ...             NaN

[3021 rows x 2 columns]

In [56]:
df_drowning=df[(df["Cause of Death"]=="Drowning")]
df_drowning[["Cause of Death","Migration route"]]

      Cause of Death                                    Migration route
6           Drowning                              Eastern Mediterranean
15          Drowning                                    Caribbean to US
24          Drowning                        Haiti to Dominican Republic
29          Drowning                   Horn of Africa to Yemen crossing
36          Drowning                   Horn of Africa to Yemen crossing
...              ...                                                ...
13001       Drowning                              Central Mediterranean
13008       Drowning                          US-Mexico border crossing
13017       Drowning  Western Africa / Atlantic route to the Canary ...
13018       Drowning  Western Africa / Atlantic route to the Canary ...
13019       Drowning  Western Africa / Atlantic route to the Canary ...

[3313 rows x 2 columns]

In [57]:
df.to_csv("Clean data Global Missing and death of Migrants data", index = False)

In [58]:
df.to_excel('Clean data Global Missing,death of Migrants data.xlsx')

In [59]:
df.isna().sum()

Incident Type                             0
Incident year                             0
Reported Month                            0
Region of Origin                          0
Region of Incident                        0
Country of Origin                         0
Number of Dead                            0
Minimum Estimated Number of Missing       0
Total Number of Dead and Missing          0
Number of Survivors                       0
Number of Females                         0
Number of Males                           0
Number of Children                        0
Cause of Death                            0
Migration route                        3021
Location of death                         0
Information Source                        8
Coordinates                              36
UNSD Geographical Grouping                1
dtype: int64

In [60]:
df_grouping=df["UNSD Geographical Grouping"].isna()
df_grouping=df[df_grouping]
df_grouping

,Incident Type,Incident year,Reported Month,Region of Origin,Region of Incident,Country of Origin,Number of Dead,Minimum Estimated Number of Missing,Total Number of Dead and Missing,Number of Survivors,Number of Females,Number of Males,Number of Children,Cause of Death,Migration route,Location of death,Information Source,Coordinates,UNSD Geographical Grouping
5360,Incident,2018,February,Latin America / Caribbean (P),North America,Unknown,1.0,0,1,0,0,1,0,Mixed or unknown,US-Mexico border crossing,Pima Country Office of the Medical Examiner ju...,NaN,"33.061615, -113.367348",NaN

In [61]:
df["UNSD Geographical Grouping"]=df["UNSD Geographical Grouping"].fillna("Uncategorized")

In [62]:
df["UNSD Geographical Grouping"].isna().sum()

0

In [63]:
df_cordi=df["Coordinates"].isna()
df_cordi=df[df_cordi]
df_cordi[["Region of Origin"	, "Region of Incident"	,"Country of Origin","Coordinates"]]

,Region of Origin,Region of Incident,Country of Origin,Coordinates
231,Unknown,Mediterranean,Unknown,NaN
256,Latin America / Caribbean (P),North America,Unknown,NaN
257,Latin America / Caribbean (P),North America,Unknown,NaN
258,Latin America / Caribbean (P),North America,Unknown,NaN
259,Latin America / Caribbean (P),North America,Unknown,NaN
260,Latin America / Caribbean (P),North America,Unknown,NaN
261,Latin America / Caribbean (P),North America,Unknown,NaN
262,Latin America / Caribbean (P),North America,Unknown,NaN
263,Latin America / Caribbean (P),North America,Unknown,NaN
264,Latin America / Caribbean (P),North America,Unknown,NaN
265,Latin America / Caribbean (P),North America,Unknown,NaN
267,Latin America / Caribbean (P),North America,Unknown,NaN
270,Latin America / Caribbean (P),North America,Unknown,NaN
271,Latin America / Caribbean (P),North America,Unknown,NaN
272,Latin America / Caribbean (P),North America,Unknown,NaN
273,Latin America / Caribbean (P),North America,Unknown,NaN
274,Latin America / Caribbean (P),North America,Unknown,NaN
275,Latin America / Caribbean (P),North America,Unknown,NaN
276,Latin America / Caribbean (P),North America,Unknown,NaN
277,Latin America / Caribbean (P),North America,Unknown,NaN
278,Latin America / Caribbean (P),North America,Unknown,NaN
279,Latin America / Caribbean (P),North America,Unknown,NaN
280,Latin America / Caribbean (P),North America,Unknown,NaN
281,Latin America / Caribbean (P),North America,Unknown,NaN
282,Latin America / Caribbean (P),North America,Unknown,NaN
283,Latin America / Caribbean (P),North America,Unknown,NaN
284,Latin America / Caribbean (P),North America,Unknown,NaN
285,Latin America / Caribbean (P),North America,Unknown,NaN
286,Latin America / Caribbean (P),North America,Unknown,NaN
287,Latin America / Caribbean (P),North America,Unknown,NaN
288,Latin America / Caribbean (P),North America,Unknown,NaN
289,Latin America / Caribbean (P),North America,Unknown,NaN
290,Latin America / Caribbean (P),North America,Unknown,NaN
291,Latin America / Caribbean (P),North America,Unknown,NaN
292,Latin America / Caribbean (P),North America,Unknown,NaN
293,Latin America / Caribbean (P),North America,Unknown,NaN

In [64]:
df["Migration route"].isna().sum()

3021

In [65]:
df["Migration route"]=df["Migration route"].fillna("Unknown")

In [66]:
df["Migration route"].isna().sum()

0

In [67]:
df["UNSD Geographical Grouping"].unique()

array(['Northern America', 'Northern Europe', 'Uncategorized',
       'Western Europe', 'Caribbean', 'South-eastern Asia',
       'Southern Asia', 'Central America', 'Eastern Africa',
       'Northern Africa', 'Eastern Asia', 'Western Asia',
       'Eastern Europe', 'Southern Europe', 'Western Africa',
       'South America', 'Southern Africa', 'Middle Africa',
       'Central Asia'], dtype=object)

In [68]:
df["UNSD Geographical Grouping"]=df["UNSD Geographical Grouping"].fillna("Uncategorized")

In [69]:
df.columns

Index(['Incident Type', 'Incident year', 'Reported Month', 'Region of Origin',
       'Region of Incident', 'Country of Origin', 'Number of Dead',
       'Minimum Estimated Number of Missing',
       'Total Number of Dead and Missing', 'Number of Survivors',
       'Number of Females', 'Number of Males', 'Number of Children',
       'Cause of Death', 'Migration route', 'Location of death',
       'Information Source', 'Coordinates', 'UNSD Geographical Grouping'],
      dtype='object')

In [70]:
df.dtypes

Incident Type                           object
Incident year                            int64
Reported Month                          object
Region of Origin                        object
Region of Incident                      object
Country of Origin                       object
Number of Dead                         float64
Minimum Estimated Number of Missing      int64
Total Number of Dead and Missing         int64
Number of Survivors                      int64
Number of Females                        int64
Number of Males                          int64
Number of Children                       int64
Cause of Death                          object
Migration route                         object
Location of death                       object
Information Source                      object
Coordinates                             object
UNSD Geographical Grouping              object
dtype: object

In [71]:
df["Incident year"]=pd.to_datetime(df["Incident year"], format='%Y')
df["Incident year"]

0       2014-01-01
1       2014-01-01
2       2014-01-01
3       2014-01-01
4       2014-01-01
           ...
13015   2023-01-01
13016   2023-01-01
13017   2023-01-01
13018   2023-01-01
13019   2023-01-01
Name: Incident year, Length: 13020, dtype: datetime64[ns]

In [72]:
df["Incident year"]=df["Incident year"].dt.year

In [73]:
df["Incident year"].unique()

array([2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023],
      dtype=int32)

In [74]:
df["Incident year"].dtypes

dtype('int32')

In [75]:
df['Incident year'] = pd.to_datetime(df['Incident year'], format='%Y')

In [76]:
df["Incident year"]

0       2014-01-01
1       2014-01-01
2       2014-01-01
3       2014-01-01
4       2014-01-01
           ...
13015   2023-01-01
13016   2023-01-01
13017   2023-01-01
13018   2023-01-01
13019   2023-01-01
Name: Incident year, Length: 13020, dtype: datetime64[ns]

In [77]:
df["Incident year"].dt.year

0        2014
1        2014
2        2014
3        2014
4        2014
         ...
13015    2023
13016    2023
13017    2023
13018    2023
13019    2023
Name: Incident year, Length: 13020, dtype: int32

In [78]:
df.columns

Index(['Incident Type', 'Incident year', 'Reported Month', 'Region of Origin',
       'Region of Incident', 'Country of Origin', 'Number of Dead',
       'Minimum Estimated Number of Missing',
       'Total Number of Dead and Missing', 'Number of Survivors',
       'Number of Females', 'Number of Males', 'Number of Children',
       'Cause of Death', 'Migration route', 'Location of death',
       'Information Source', 'Coordinates', 'UNSD Geographical Grouping'],
      dtype='object')

In [79]:
df["Reported Month"].unique()

array(['January', 'February', 'March', 'April', 'May', 'June', 'July',
       'August', 'September', 'October', 'November', 'December'],
      dtype=object)

In [80]:
df["Reported Month"].dtypes

dtype('O')

In [81]:
df.dtypes

Incident Type                                  object
Incident year                          datetime64[ns]
Reported Month                                 object
Region of Origin                               object
Region of Incident                             object
Country of Origin                              object
Number of Dead                                float64
Minimum Estimated Number of Missing             int64
Total Number of Dead and Missing                int64
Number of Survivors                             int64
Number of Females                               int64
Number of Males                                 int64
Number of Children                              int64
Cause of Death                                 object
Migration route                                object
Location of death                              object
Information Source                             object
Coordinates                                    object
UNSD Geographical Grouping                     object
dtype: object

In [82]:
df["Number of Dead"]=df["Number of Dead"].astype(int)
df["Number of Dead"].dtypes

dtype('int64')

In [83]:
#Checking for negative since I saw some in excel file
df_negative=df[(df["Number of Dead"]<0) |
               (df["Minimum Estimated Number of Missing"]<0)|
               (df["Total Number of Dead and Missing"]<0)|
               (df["Number of Survivors"]<0)|
               (df["Number of Females"]<0)|
               (df["Number of Males"]<0)|
                (df["Number of Children"]<0)]
df_negative[["Number of Dead","Minimum Estimated Number of Missing","Total Number of Dead and Missing","Number of Survivors","Number of Females","Number of Males","Number of Children"]]

,Number of Dead,Minimum Estimated Number of Missing,Total Number of Dead and Missing,Number of Survivors,Number of Females,Number of Males,Number of Children
601,20,-1,19,1,0,1,1
806,15,-2,13,0,6,3,6
858,57,-1,56,274,7,17,20
1247,1,56,57,-1,0,1,0
7794,1,0,1,-1,1,0,0
7796,1,0,1,-1,0,1,0
7800,1,0,1,-1,1,0,0
7889,2,0,2,-2,0,2,0
10422,2,-1,1,0,0,2,0

In [84]:
df["Minimum Estimated Number of Missing"]=df["Minimum Estimated Number of Missing"].abs()

In [85]:
df.loc[1247,"Number of Survivors"] = "-1"
df.loc[7749,"Number of Survivors"] = "-1"
df.loc[7796,"Number of Survivors"] = "-1"
df.loc[7800,"Number of Survivors"] = "-1"
df.loc[7889,"Number of Survivors"] = "-2"

<ipython-input-85-fbfe53e2f1b0>:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '-1' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[1247,"Number of Survivors"] = "-1"

In [86]:
df["Number of Survivors"]=pd.to_numeric(df["Number of Survivors"])

In [87]:
#Checking for negative since I saw some in excel file
df_negative=df[(df["Number of Dead"]<0) |
               (df["Minimum Estimated Number of Missing"]<0)|
               (df["Total Number of Dead and Missing"]<0)|
               (df["Number of Survivors"]<0)|
               (df["Number of Females"]<0)|
               (df["Number of Males"]<0)|
                (df["Number of Children"]<0)]
df_negative[["Number of Dead","Minimum Estimated Number of Missing","Total Number of Dead and Missing","Number of Survivors","Number of Females","Number of Males","Number of Children"]]

,Number of Dead,Minimum Estimated Number of Missing,Total Number of Dead and Missing,Number of Survivors,Number of Females,Number of Males,Number of Children
1247,1,56,57,-1,0,1,0
7749,1,0,1,-1,0,1,0
7794,1,0,1,-1,1,0,0
7796,1,0,1,-1,0,1,0
7800,1,0,1,-1,1,0,0
7889,2,0,2,-2,0,2,0

In [88]:
df["Number of Survivors"].dtypes

dtype('int64')

In [89]:
df.loc[df["Number of Survivors"]<0,"Number of Survivors"]=0

In [90]:
#Checking for negative since I saw some in excel file
df_negative=df[(df["Number of Dead"]<0) |
               (df["Minimum Estimated Number of Missing"]<0)|
               (df["Total Number of Dead and Missing"]<0)|
               (df["Number of Survivors"]<0)|
               (df["Number of Females"]<0)|
               (df["Number of Males"]<0)|
                (df["Number of Children"]<0)]
df_negative[["Number of Dead","Minimum Estimated Number of Missing","Total Number of Dead and Missing","Number of Survivors","Number of Females","Number of Males","Number of Children"]]

Empty DataFrame
Columns: [Number of Dead, Minimum Estimated Number of Missing, Total Number of Dead and Missing, Number of Survivors, Number of Females, Number of Males, Number of Children]
Index: []

In [91]:
df.to_csv("Clean data final",index=False)

In [92]:
df.to_excel("Clean data final.xlsx",index=False)

In [93]:
df["Incident year"]

0       2014-01-01
1       2014-01-01
2       2014-01-01
3       2014-01-01
4       2014-01-01
           ...
13015   2023-01-01
13016   2023-01-01
13017   2023-01-01
13018   2023-01-01
13019   2023-01-01
Name: Incident year, Length: 13020, dtype: datetime64[ns]

In [94]:
df["Incident year"]=df["Incident year"].dt.year

In [95]:
df["Incident year"]

0        2014
1        2014
2        2014
3        2014
4        2014
         ...
13015    2023
13016    2023
13017    2023
13018    2023
13019    2023
Name: Incident year, Length: 13020, dtype: int32

In [96]:
df.to_csv("Clean data final",index=False)

In [97]:
df.to_excel("Clean data final.xlsx",index=False)

##Analysis

### Incident Heatmap

In [98]:
import matplotlib.pyplot as plt
import seaborn as sns

In [99]:
df.columns

Index(['Incident Type', 'Incident year', 'Reported Month', 'Region of Origin',
       'Region of Incident', 'Country of Origin', 'Number of Dead',
       'Minimum Estimated Number of Missing',
       'Total Number of Dead and Missing', 'Number of Survivors',
       'Number of Females', 'Number of Males', 'Number of Children',
       'Cause of Death', 'Migration route', 'Location of death',
       'Information Source', 'Coordinates', 'UNSD Geographical Grouping'],
      dtype='object')

In [100]:
df["Coordinates"].isna().sum()

36

In [101]:
df["Coordinates"].head()

0    31.650259, -110.366453
1      31.59713, -111.73756
2      31.94026, -113.01125
3    31.506777, -109.315632
4               59.1551, 28
Name: Coordinates, dtype: object

In [102]:
df["Coordinates"].dropna()

0         31.650259, -110.366453
1           31.59713, -111.73756
2           31.94026, -113.01125
3         31.506777, -109.315632
4                    59.1551, 28
                  ...
13015     40.91271268, 26.369657
13016     41.71697242, 26.351489
13017    23.72836078, -15.901632
13018     35.17187365, -2.903182
13019    14.71870705, -17.506255
Name: Coordinates, Length: 12984, dtype: object

In [103]:
df[["Latitude","Longitude"]]=df["Coordinates"].str.split(',',expand = True)
df['Latitude']=df["Latitude"].astype(float)
df["Longitude"]=df["Longitude"].astype(float)

In [104]:
df[["Latitude","Longitude"]]

        Latitude   Longitude
0      31.650259 -110.366453
1      31.597130 -111.737560
2      31.940260 -113.011250
3      31.506777 -109.315632
4      59.155100   28.000000
...          ...         ...
13015  40.912713   26.369657
13016  41.716972   26.351489
13017  23.728361  -15.901632
13018  35.171874   -2.903182
13019  14.718707  -17.506255

[13020 rows x 2 columns]

In [105]:
geo_data=df.groupby(["Latitude","Longitude"]).size().reset_index(name="Incedent Count")
geo_data

       Latitude  Longitude  Incedent Count
0    -37.462916 -72.361225               1
1    -36.824943 -73.037945               1
2    -36.236267 -72.062608               1
3    -35.853050 -71.183332               1
4    -35.432707 -71.665835               1
...         ...        ...             ...
9577  56.090999  27.946380               2
9578  56.507839  27.342859               1
9579  59.155100  28.000000               1
9580  62.544340  31.007590               1
9581  66.929981  30.231360               1

[9582 rows x 3 columns]

In [106]:
geo_data=df.groupby(["Latitude","Longitude"]).size().reset_index(name="Incident Count")
geo_data

       Latitude  Longitude  Incident Count
0    -37.462916 -72.361225               1
1    -36.824943 -73.037945               1
2    -36.236267 -72.062608               1
3    -35.853050 -71.183332               1
4    -35.432707 -71.665835               1
...         ...        ...             ...
9577  56.090999  27.946380               2
9578  56.507839  27.342859               1
9579  59.155100  28.000000               1
9580  62.544340  31.007590               1
9581  66.929981  30.231360               1

[9582 rows x 3 columns]

In [107]:
!pip install geopandas matplotlib descartes

Requirement already satisfied: geopandas in /usr/local/lib/python3.10/dist-packages (1.0.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (3.8.0)
Collecting descartes
  Downloading descartes-1.1.0-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: numpy>=1.22 in /usr/local/lib/python3.10/dist-packages (from geopandas) (1.26.4)
Requirement already satisfied: pyogrio>=0.7.2 in /usr/local/lib/python3.10/dist-packages (from geopandas) (0.10.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from geopandas) (24.2)
Requirement already satisfied: pandas>=1.4.0 in /usr/local/lib/python3.10/dist-packages (from geopandas) (2.2.2)
Requirement already satisfied: pyproj>=3.3.0 in /usr/local/lib/python3.10/dist-packages (from geopandas) (3.7.0)
Requirement already satisfied: shapely>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from geopandas) (2.0.6)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (4.55.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (1.4.7)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (11.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.4.0->geopandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.4.0->geopandas) (2024.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from pyogrio>=0.7.2->geopandas) (2024.8.30)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Downloading descartes-1.1.0-py3-none-any.whl (5.8 kB)
Installing collected packages: descartes
Successfully installed descartes-1.1.0

In [108]:
import geopandas as gpd

In [109]:
from shapely.geometry import Point
geometry=[Point(xy) for xy in zip(geo_data["Longitude"],geo_data["Latitude"])]
geo_df=gpd.GeoDataFrame(geo_data,geometry=geometry)

In [110]:
!pip install --upgrade geopandas

Requirement already satisfied: geopandas in /usr/local/lib/python3.10/dist-packages (1.0.1)
Requirement already satisfied: numpy>=1.22 in /usr/local/lib/python3.10/dist-packages (from geopandas) (1.26.4)
Requirement already satisfied: pyogrio>=0.7.2 in /usr/local/lib/python3.10/dist-packages (from geopandas) (0.10.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from geopandas) (24.2)
Requirement already satisfied: pandas>=1.4.0 in /usr/local/lib/python3.10/dist-packages (from geopandas) (2.2.2)
Requirement already satisfied: pyproj>=3.3.0 in /usr/local/lib/python3.10/dist-packages (from geopandas) (3.7.0)
Requirement already satisfied: shapely>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from geopandas) (2.0.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.4.0->geopandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.4.0->geopandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.4.0->geopandas) (2024.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from pyogrio>=0.7.2->geopandas) (2024.8.30)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas>=1.4.0->geopandas) (1.16.0)

In [111]:
world = gpd.read_file("/content/world-administrative-boundaries.geojson")

DataSourceError: /content/world-administrative-boundaries.geojson: No such file or directory

In [ ]:
world.head()

In [ ]:
fig, ax = plt.subplots(figsize=(14, 10))
world.plot(ax=ax, color='whitesmoke', edgecolor='grey')
geo_df.plot(ax=ax, marker='o', color='red', markersize=5)
plt.title('Incident Locations on World Map')
plt.xlabel('Longitude')
plt.ylabel('Latitude')
plt.show()

In [ ]:
geo_df.crs= 'epsg:4326'

In [ ]:
!pip install contextily
import contextily as ctx

In [ ]:
fig1, ax = plt.subplots(figsize=(30,30))
world.to_crs(epsg=3857).plot(ax=ax, alpha=0.2, color="lightgrey",edgecolor="grey")
ctx.add_basemap(ax, source=ctx.providers.CartoDB.Positron)
geo_df.to_crs(epsg=3857).plot(ax=ax, marker='o', color='red', markersize=10, alpha=0.7)
plt.title('Incident Locations on World Map',fontsize=30)
plt.xlabel('Longitude')
plt.ylabel('Latitude')
plt.show()

In [ ]:
fig1.savefig("1incident_heatmap.png") # Save as png

###Migration Route

In [ ]:
df["Migration route"].unique()

In [ ]:
df.columns

In [ ]:
df_migration = df.groupby(["Latitude","Longitude"]).size().reset_index(name="Migration route")
df_migration

In [ ]:
df_migration1= df.groupby(["Latitude","Longitude","Migration route"])[["Latitude","Longitude"]].size().sort_values(ascending=False)
df_migration1.head(20)

In [ ]:
df_migration1= df.groupby(["Migration route"])[["Latitude","Longitude"]].size().sort_values(ascending=False)
df_migration1

In [ ]:
df_migration1=df_migration1.rename("frequency")
df_migration1=df_migration1.head(10)
df_migration1

In [ ]:
import seaborn as sns

sns.set_style("darkgrid")
palette=sns.color_palette("muted")
fig3,ax=plt.subplots(figsize=(10,10))
bars=ax.bar(df_migration1.index,
            height=df_migration1.values,
            color=palette,
            edgecolor="black",
            width=0.8
                  )
ax.bar_label(bars)
plt.title("Migration Route", fontsize=16)
plt.xlabel("Migration Route", fontsize=12)
plt.ylabel("frequency", fontsize=12)
plt.xticks(rotation=45, ha="right", fontsize=10)
plt.tight_layout()
plt.show()

In [ ]:
fig3.savefig("Migration Route bar")

### Number analysis

#### Demographics Analysis

In [ ]:
df.head()

In [ ]:
df.columns

In [ ]:
df[["Number of Males","Number of Females","Number of Children"]].isna().sum()

In [ ]:
df_analysis=pd.concat([df["Number of Males"],df["Number of Females"],df["Number of Children"]],axis=1)
df_analysis

In [ ]:
sums=df_analysis.sum()
sums

In [ ]:
fig3,ax=plt.subplots(figsize=(10,10))
sns.set_style("darkgrid")
palette=sns.color_palette("muted")
ax.pie(sums,labels=sums.index,autopct="%1.1f%%")
ax.set_title("Demographics of Incidents")
ax.axis('equal')
plt.show()

In [ ]:
fig3.savefig("Demographics of Incidents")

#### Region wise death

In [ ]:
df.head()

In [ ]:
df.columns

In [ ]:
df_death=df[["Region of Incident","Number of Dead"]]
df_death

In [ ]:
df_death1=df_death.groupby("Region of Incident")["Number of Dead"].sum().sort_values(ascending=False)
df_death1=df_death1.head(10)
df_death1

In [ ]:
sns.set_style("darkgrid")
sns.set_palette("muted")
palette=sns.color_palette("pastel")
fig4,ax=plt.subplots(figsize=(10,10))
bars=ax.bar(df_death1.index,height=df_death1.values,color=palette,edgecolor="black")
ax.bar_label(bars)
plt.title("Region-wise deaths (Top 10)",fontsize=16)
plt.xlabel("Region of Incident",fontsize=12)
plt.ylabel("Number of Dead",fontsize=12)
plt.xticks(rotation=45,ha="right",fontsize=10)
plt.tight_layout()
plt.show()

In [ ]:
fig4.savefig("1Region-wise deaths (Top 10)")

#### Causes of death

In [ ]:
df.columns

In [ ]:
df_cause=df[["Cause of Death","Number of Dead"]]
df_cause=df_cause.set_index("Cause of Death")
df_cause

In [ ]:
df_cause=df_cause.groupby("Cause of Death")["Number of Dead"].sum().sort_values(ascending = False)
df_cause1=df_cause.head(5)
df_cause1

In [ ]:
fig5,ax=plt.subplots(figsize=(10,10))
sns.set_style("darkgrid")
palette=sns.set_palette("pastel")
ax.pie(df_cause1,autopct="%1.1f%%")
ax.set_title("Causes of Death (Top 5)",fontsize=16)
plt.legend(df_cause1.index,loc="upper right")
ax.axis("equal")
plt.show()

In [ ]:
fig5.savefig("1Causes of Death (Top 5)")

#### Drowning Analysis

In [ ]:
df.columns

In [ ]:
df_exp1=df[df["Cause of Death"]=="Drowning"]
df_exp1[["Region of Incident","Number of Dead","Number of Survivors","Latitude","Longitude"]]

In [ ]:
df_exp1_size=df_exp1.groupby("Region of Incident")["Number of Dead"].sum().sort_values(ascending=False)
df_exp1_size=df_exp1_size.head(10)
df_exp1_size

In [ ]:
fig6,ax=plt.subplots(figsize=(10,10))
sns.set_style("darkgrid")
palette=sns.color_palette("pastel")
bars=ax.bar(df_exp1_size.index,height=df_exp1_size.values,color=palette,edgecolor="white")
ax.bar_label(bars)
plt.title("Region-wise deaths by drowning (Top 10)",fontsize=16)
plt.xlabel("Region of incidents",fontsize=12)
plt.ylabel("Number of Dead",fontsize=12)
plt.xticks(rotation=45,ha="right",fontsize=10)
plt.tight_layout()
plt.show()

In [ ]:
df_expDead=df_exp1[["Number of Dead","Latitude","Longitude"]]
df_expDead

In [ ]:
from shapely.geometry import Point
geometry=[Point(xy) for xy in zip(df_expDead["Longitude"],df_expDead["Latitude"])]
geo_dead=gpd.GeoDataFrame(df_expDead,geometry=geometry)

In [ ]:
geo_dead

In [ ]:
world.head()

In [ ]:
geo_dead.crs='epsg:4326'

In [ ]:
fig7,ax=plt.subplots(figsize=(30,30))
world.to_crs(epsg=3857).plot(ax=ax,alpha=0.2,color="lightgrey",edgecolor="grey")
geo_dead.to_crs(epsg=3857).plot(ax=ax,alpha=1,color="blue",marker='o',markersize=5)
ctx.add_basemap(ax, source=ctx.providers.CartoDB.Positron)
plt.title('Death by drowning during migration',fontsize=10)
plt.xlabel('Longitude')
plt.ylabel('Latitude')
plt.show()

In [ ]:
fig6.savefig("1Death by drowning during migration bar")

In [ ]:
fig7.savefig("Death by drowning during migration")

#### Time line analysis

In [ ]:
df.columns

In [ ]:
df[["Incident year","Number of Dead","Number of Survivors","Minimum Estimated Number of Missing"]]

In [ ]:
df_year_dead=df.groupby("Incident year")["Number of Dead"].sum()
df_year_dead

In [ ]:
sns.set_style("whitegrid")
palette=sns.color_palette("pastel")
fig8,ax=plt.subplots(figsize=(15,8))
bars=sns.lineplot(ax=ax,x=df_year_dead.index,y=df_year_dead.values,color="skyblue")
ax.set_title("Number of Dead per year",fontsize=16)
plt.title("Death over the year due to migration",fontsize=16)
plt.xlabel("Year",fontsize=12)
plt.ylabel("Number of Dead",fontsize=12)

In [ ]:
df_year_dead1=df.groupby("Incident year")["Number of Survivors"].sum()
df_year_dead1

In [ ]:
df_year_dead2=df.groupby("Incident year")["Minimum Estimated Number of Missing"].sum()
df_year_dead2

In [ ]:
df_year_final=pd.concat([df_year_dead,df_year_dead1,df_year_dead2],axis=1)
df_year_final

In [ ]:
sns.set_style("whitegrid")
palette=sns.color_palette("pastel")
fig9,ax=plt.subplots(figsize=(15,8))
df_year_final.plot(ax=ax,kind="line",color=["red","green","blue"])
plt.title("Dead vs Survivors vs Missing over the years",fontsize=16)
plt.xlabel("Year",fontsize=12)
plt.ylabel("Total",fontsize=12)

In [ ]:
fig8.savefig("Number of Dead per year")

In [ ]:
fig9.savefig("Dead,survivors,missing")

####Region of Origin

In [ ]:
df.columns

In [ ]:
df.head()

In [ ]:
df["Incident"]=df["Total Number of Dead and Missing"]+df["Number of Survivors"]
df["Incident"].count()

In [ ]:
df[["Region of Origin","Region of Incident","Incident"]]

In [ ]:
df_migrating=df.groupby("Region of Origin")["Incident"].size().sort_values(ascending=False)
df_migrating=df_migrating.head(10)
df_migrating
df_migrating=df_migrating.reset_index().set_index("Region of Origin")
df_migrating

In [ ]:
sns.set_style("whitegrid")
palette=sns.color_palette("pastel")
fig10,ax=plt.subplots(figsize=(10,10))
bars=ax.bar(df_migrating.index,df_migrating["Incident"],color=palette,edgecolor="white")
ax.bar_label(bars)
plt.title("Region of Origin",fontsize=16)
plt.xlabel("Region of Origin",fontsize=12)
plt.ylabel("Incident",fontsize=12)
plt.xticks(rotation=45,ha="right",fontsize=10)

In [ ]:
fig10.savefig("Migrating Region")

####Country affected with highest migration incident

In [ ]:
df.columns

In [ ]:
df_incident_region=df[["Incident year","Region of Incident","Incident"]]
df_incident_region

In [ ]:
df_incident_region1=df_incident_region.groupby(["Region of Incident"])["Incident"].size().sort_values(ascending=False)
df_incident_region1=df_incident_region1.head(10)
df_incident_region1

In [ ]:
df_north=df[(df["Region of Incident"]=="North America")]
df_north=df_north[["Region of Incident","Incident year","Incident","Number of Dead","Minimum Estimated Number of Missing","Number of Survivors"]]
df_north=df_north[["Incident year","Incident","Number of Dead","Minimum Estimated Number of Missing","Number of Survivors"]]
df_north=df_north.set_index("Incident year")
df_north

In [ ]:
sns.set_style("whitegrid")
palette=sns.color_palette("pastel")
fig11,ax=plt.subplots(figsize=(15,8))
sns.lineplot(x="Incident year",y="Incident",ax=ax,data=df_north,label="Incident")
sns.lineplot(x="Incident year",y="Number of Dead",ax=ax,data=df_north,label="Number of Dead")
sns.lineplot(x="Incident year",y="Number of Survivors",ax=ax,data=df_north,label="Number of Survivors")
plt.title("North America",fontsize=16)
plt.show()

In [ ]:
fig11.savefig("North America Migration trend over the year")

#### 2nd Round of Analysis

In [ ]:
df.head()

In [ ]:
df.columns

####Incident graph

In [ ]:
df.columns

In [ ]:
df_incident = df[["Region of Incident","Incident"]]
df_incident

In [ ]:
df_incident=df_incident.groupby("Region of Incident")["Incident"].size().sort_values(ascending=False)
df_incident=df_incident.head(5)
df_incident

In [ ]:
sns.set_style("whitegrid")
palette=sns.color_palette("pastel")
fig13,ax=plt.subplots(figsize=(10,10))
bars=ax.bar(df_incident.index,df_incident.values,color=palette,edgecolor="white")
ax.bar_label(bars)
plt.title("Incident per Region",fontsize=16)
plt.xlabel("Region of Incident",fontsize=12)
plt.xticks(rotation=45, ha="right", fontsize=10)
plt.tight_layout()
plt.ylabel("Incident",fontsize=12)

In [ ]:
fig13.savefig("1Incident per Region")

#### Safest Migration route

In [ ]:
df.columns

In [ ]:
df_saferoute=df[["Migration route","Number of Survivors","Incident"]]
df_saferoute

In [ ]:
df_saferoute["%survivor"]=df_saferoute["Number of Survivors"]/df_saferoute["Incident"]*100
df_saferoute=df_saferoute.round(2)
df_saferoute

In [ ]:
df_saferoute=df_saferoute.groupby("Migration route")["%survivor"].mean().round(2)
df_saferoute=df_saferoute
df_saferoute

In [ ]:
df_deadlyroute=df[["Migration route","Number of Dead","Incident"]]
df_deadlyroute

In [ ]:
df_deadlyroute["%dead"]=df_deadlyroute["Number of Dead"]/df_deadlyroute["Incident"]*100
df_deadlyroute=df_deadlyroute.round(2)
df_deadlyroute

In [ ]:
df_deadlyroute=df_deadlyroute.groupby("Migration route")["%dead"].mean().round(2)
df_deadlyroute=df_deadlyroute
df_deadlyroute

In [ ]:
df_route=pd.concat([df_saferoute,df_deadlyroute],axis=1)
df_route=df_route.reset_index()
df_route

In [ ]:
selected_routes = ["Afghanistan to Iran","Central Mediterranean","Sahara Desert crossing", "unknown","US-Mexico border crossing"]
df_route_filtered = df_route[df_route["Migration route"].isin(selected_routes)]
df_route_filtered

In [ ]:
fig16, ax = plt.subplots(figsize=(10, 6))
width = 0.35
rects1 = ax.bar(df_route_filtered['Migration route'],
                df_route_filtered['%survivor'],
                width,
                label='% Survivor')
rects2 = ax.bar(df_route_filtered['Migration route'],
                df_route_filtered['%dead'],
                width,
                bottom=df_route_filtered['%survivor'],
                label='% Dead')
def autolabel(rects):
    for rect in rects:
        height = rect.get_height()
        ax.annotate('{:.1f}'.format(height),
                    xy=(rect.get_x() + rect.get_width() / 2, rect.get_y() + height / 2),
                    xytext=(0, 3),
                    textcoords="offset points",
                    ha='center', va='bottom')
autolabel(rects1)
autolabel(rects2)
ax.set_xlabel('Migration Route')
ax.set_ylabel('Percentage')
ax.set_title('Percentage of Survivors and Dead per Migration Route')
ax.legend()
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()

In [ ]:
fig16.savefig("Safest vs deadliest Migration Route")